### PR TITLE
Add missing SysTick_Disable prototype

### PR DESCRIPTION
**Pull request by monkbroc**
Running `make all PARTICLE_DEVELOP=1 PLATFORM=photon` from the firmware root folder fails with `implicit declaration of function 'SysTick_Disable'` in `bootloader/src/main.c`

### CODE REVIEW

**Comment by technobly** [comment]
I'm not sure if compiling from the firmware/ folder is or should be supported.  I only use main/, modules/ and bootloader/.  cc: @m-mcgowan

**Comment by monkbroc** [comment]
A valid point, but the error still occurs when compiling from `bootloader/

**Comment by technobly** [comment]
That's strange.  Thanks for raising this issue... will have to see if this is a recent regression or something with the makefile.

**Comment by m-mcgowan** [comment]
This was a regression with changes I made when implementing `micros()` in #493 where I removed SysTick_Disable() from the header, getting ready to refactor. I think I may have been interrupted part way through this. The commit above addresses the issue. Thanks for reporting!
