### PR TITLE
arm gcc 5.3.1 compatibility

### LINKED ISSUE #963: isascii not declared in this scope
< Please summarize your issue here.  Check [x] as many boxes below as you can before submitting your issue.  Thanks -- you rock! >

On macOSX El Capitan with gcc-arm-none-eabi-5_3-2016q1 I am getting the error 
`../wiring/inc/spark_wiring_character.h:49:31: error: 'isascii' was not declared in this scope`
`/wiring/inc/spark_wiring_character.h:104:21: error: 'toascii' was not declared in this scope`
running make clean all
---

Completeness:
- [ x] Minimum test case added
- [ x] Device, system and user firmware versions stated
- [x] Particle confirmed

### PR DESCRIPTION
**Pull request by m-mcgowan**
adds GNU suport (for isascii and toascii) and avoids duplicate symbol definitions on linux. Provides compatibility with arm gcc 5.3.1 and fixes #963

---

Doneness:

- [x] Contributor has signed CLA
- [x] Problem and Solution clearly stated
- [ ] Code peer reviewed
- [x] API tests compiled
- [ ] Run unit/integration/application tests on device
- [ ] Add documentation
- [ ] Add to CHANGELOG.md after merging (add links to docs and issues)
…

### CODE REVIEW

**Comment by m-mcgowan** [comment]
To test:

[ ] - firmware builds on 5.3.1
[ ] - Core can connect to the cloud
